import Logo from "./logo.png"
import LogoInverted from "./logo_inverted.png"
import LogoClient1 from "./client1.png"
import LogoClient2 from "./client2.png"
import LogoClient3 from "./client3.png"
import LogoClient4 from "./client4.png"
import LogoClient5 from "./client5.png"
import IconService1 from "./service1.png"
import IconService2 from "./service2.png"
import IconService3 from "./service3.png"
import IconService4 from "./service4.png"
import IconService5 from "./service5.png"
import IconService6 from "./service6.png"

export {Logo, LogoInverted, LogoClient1, LogoClient2, LogoClient3, LogoClient4, LogoClient5, IconService1, IconService2, IconService3, IconService4, IconService5, IconService6}
